services:
  - type: web
    name: contentful-hf-app
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10
